version: '3.4'

services:

  postgres:
    image: postgres:12.7
    ports:
      - "5432"
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "mypassword"
      POSTGRES_DB: "twitch"

  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    environment:
      - KAFKA_ADVERTISED_LISTENERS=INSIDE://:9092,OUTSIDE://localhost:9094
      - KAFKA_LISTENERS=INSIDE://:9092,OUTSIDE://:9094
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_BROKER_ID=0
      - KAFKA_AUTO_LEADER_REBALANCE_ENABLE=false
      - KAFKA_CREATE_TOPICS=priv.hello.twitch.ping:1:1,priv.hello.twitch.pong:1:1
    ports:
      - "9094:9094"
    links:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181"
