version: '3.4'

services:

  postgres:
    image: postgres:12.7
    ports:
      - "5432"
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "mypassword"
      POSTGRES_DB: "twitch"
