spring:
  main:
    banner-mode: "OFF"
    cloud-platform: kubernetes
  profiles:
    active: dev
  datasource:
    url: "jdbc:postgresql://${database.host}:${database.port}/twitch"
    username: "root"
    password: "${database.password}"

database:
  host: localhost
  port: 5432
  password: "mypassword"

server:
  port: 8000
  compression:
    enabled: true
    mime-types: application/json

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: metrics,info,health

schibsted:
  autoconfig:
    logging:
      ownerteam: "hello-twitch-team"

springfox.documentation.open-api.v3.path: /schema
